import sounds from '../sounds/sounds.js';
import images from './images.js';
import spriteTypes from './spriteTypes.js';

const riverDefault = {
  image: images.WATER,
  sound: sounds.RIVER,
  frameCount: 7,
  speed: 7
};

const treeDefault = {
  image: images.TREES,
  sound: sounds.FOREST,
  frameCount: 4,
  speed: 4
};

const bigTreeDefault = {
  ...treeDefault,
  speed: 0,
  width: 26,
  height: 41,
  offsetX: -13,
  offsetY: -40,
};

const sprites = {
  [spriteTypes.WAVES]: {
    image: images.WATER,
    sound: sounds.WAVES,
    x: 0,
    y: 0,
    width: 28,
    height: 13,
    offsetX: 9,
    offsetY: 23,
    frameCount: 7,
    speed: 3
  },
  [spriteTypes.RIVER_SPRING_EAST]: {
    ...riverDefault,
    x: 500,
    y: 0,
    width: 30,
    height: 19,
    offsetX: 16,
    offsetY: 19,
  },
  [spriteTypes.RIVER_SPRING_SOUTH]: {
    ...riverDefault,
    x: 530,
    y: 0,
    width: 26,
    height: 19,
    offsetX: 9,
    offsetY: 20,
  },
  [spriteTypes.RIVER_SPRING_NORTH]: {
    ...riverDefault,
    x: 556,
    y: 0,
    width: 25,
    height: 16,
    offsetX: 19,
    offsetY: 19,
  },
  [spriteTypes.RIVER_SPRING_WEST]: {
    ...riverDefault,
    x: 581,
    y: 0,
    width: 25,
    height: 15,
    offsetX: 8,
    offsetY: 21,
  },
  [spriteTypes.RIVER_MOUTH_WEST]: {
    ...riverDefault,
    x: 336,
    y: 0,
    width: 42,
    height: 22,
    offsetX: 2,
    offsetY: 17,
  },
  [spriteTypes.RIVER_MOUTH_NORTH]: {
    ...riverDefault,
    x: 378,
    y: 0,
    width: 40,
    height: 22,
    offsetX: 10,
    offsetY: 17,
  },
  [spriteTypes.RIVER_MOUTH_EAST]: {
    ...riverDefault,
    x: 418,
    y: 0,
    width: 40,
    height: 22,
    offsetX: 10,
    offsetY: 21,
  },
  [spriteTypes.RIVER_MOUTH_SOUTH]: {
    ...riverDefault,
    x: 458,
    y: 0,
    width: 42,
    height: 22,
    offsetX: 2,
    offsetY: 21,
  },
  [spriteTypes.RIVER_NORTH_EAST]: {
    ...riverDefault,
    x: 250,
    y: 0,
    width: 18,
    height: 18,
    offsetX: 26,
    offsetY: 21,
  },
  [spriteTypes.RIVER_NORTH_SOUTH]: {
    ...riverDefault,
    x: 198,
    y: 0,
    width: 34,
    height: 18,
    offsetX: 10,
    offsetY: 21,
  },
  [spriteTypes.RIVER_WEST_NORTH]: {
    ...riverDefault,
    x: 268,
    y: 0,
    width: 34,
    height: 15,
    offsetX: 10,
    offsetY: 20,
  },
  [spriteTypes.RIVER_SOUTH_EAST]: {
    ...riverDefault,
    x: 302,
    y: 0,
    width: 34,
    height: 13,
    offsetX: 10,
    offsetY: 26,
  },
  [spriteTypes.RIVER_WEST_EAST]: {
    ...riverDefault,
    x: 164,
    y: 0,
    width: 34,
    height: 18,
    offsetX: 10,
    offsetY: 21,
  },
  [spriteTypes.RIVER_WEST_SOUTH]: {
    ...riverDefault,
    x: 232,
    y: 0,
    width: 18,
    height: 18,
    offsetX: 10,
    offsetY: 21,
  },
  [spriteTypes.RIVER_SLOPE_NORTH]: {
    ...riverDefault,
    x: 28,
    y: 0,
    width: 34,
    height: 8,
    offsetX: 10,
    offsetY: 18,
  },
  [spriteTypes.RIVER_SLOPE_EAST]: {
    ...riverDefault,
    x: 130,
    y: 0,
    width: 34,
    height: 34,
    offsetX: 10,
    offsetY: 5,
  },
  [spriteTypes.RIVER_SLOPE_SOUTH]: {
    ...riverDefault,
    x: 96,
    y: 0,
    width: 34,
    height: 34,
    offsetX: 10,
    offsetY: 5,
  },
  [spriteTypes.RIVER_SLOPE_WEST]: {
    ...riverDefault,
    x: 62,
    y: 0,
    width: 34,
    height: 8,
    offsetX: 10,
    offsetY: 19,
  },
  [spriteTypes.RIVER_DAM_NORTH_EAST]: {
    ...riverDefault,
    x: 268,
    y: 105,
    width: 33,
    height: 23,
    offsetX: 11,
    offsetY: 16,
  },
  [spriteTypes.RIVER_DAM_NORTH_SOUTH]: {
    ...riverDefault,
    x: 199,
    y: 126,
    width: 34,
    height: 23,
    offsetX: 10,
    offsetY: 16,
  },
  [spriteTypes.RIVER_DAM_WEST_NORTH]: {
    ...riverDefault,
    x: 302,
    y: 91,
    width: 34,
    height: 17,
    offsetX: 10,
    offsetY: 20,
  },
  [spriteTypes.RIVER_DAM_SOUTH_EAST]: {
    ...riverDefault,
    x: 336,
    y: 154,
    width: 35,
    height: 23,
    offsetX: 10,
    offsetY: 16,
  },
  [spriteTypes.RIVER_DAM_WEST_EAST]: {
    ...riverDefault,
    x: 164,
    y: 126,
    width: 35,
    height: 22,
    offsetX: 10,
    offsetY: 17,
  },
  [spriteTypes.RIVER_DAM_WEST_SOUTH]: {
    ...riverDefault,
    x: 233,
    y: 126,
    width: 34,
    height: 22,
    offsetX: 10,
    offsetY: 17,
  },
  [spriteTypes.TREE_HARDWOOD]: {
    ...treeDefault,
    x: 0,
    y: 0,
    width: 21,
    height: 26,
    offsetX: -11,
    offsetY: -26,
  },
  [spriteTypes.TREE_PALM]: {
    ...treeDefault,
    x: 21,
    y: 0,
    width: 21,
    height: 26,
    offsetX: -12,
    offsetY: -26,
  },
  [spriteTypes.TREE_EVERGREEN]: {
    ...treeDefault,
    x: 42,
    y: 0,
    width: 22,
    height: 27,
    offsetX: -12,
    offsetY: -27,
  },
  [spriteTypes.TREE_SMALL]: {
    ...treeDefault,
    x: 64,
    y: 0,
    width: 17,
    height: 16,
    offsetX: -9,
    offsetY: -16,
  },
  [spriteTypes.BUSH]: {
    ...treeDefault,
    frameCount: 3,
    speed: 0,
    x: 81,
    y: 0,
    width: 20,
    height: 13,
    offsetX: -10,
    offsetY: -13,
  },
  [spriteTypes.BIG_TREE]: {
    ...bigTreeDefault,
    frameCount: 1,
    x: 238,
    y: 0,
  },
  [spriteTypes.BIG_TREE_WITH_LADDER]: {
    ...bigTreeDefault,
    image: images.BUILDINGS,
    frameCount: 5,
    x: 161,
    y: 0,
  },
  [spriteTypes.BIG_TREE_WITH_PLATFORM]: {
    ...bigTreeDefault,
    image: images.BUILDINGS,
    frameCount: 6,
    x: 187,
    y: 0,
    width: 34,
  },
  [spriteTypes.BIG_TREE_WITH_TREE_HOUSE]: {
    ...bigTreeDefault,
    image: images.BUILDINGS,
    frameCount: 6,
    x: 221,
    y: 0,
    width: 34,
  },
  [spriteTypes.PIRATE_WRECK]: {
    image: images.BUILDINGS,
    sound: sounds.WAVES,
    x: 415,
    y: 0,
    width: 27,
    height: 26,
    offsetX: -17,
    offsetY: -23,
    frameCount: 3,
    speed: 5,
  },
  [spriteTypes.SHIP_WRECK]: {
    image: images.BUILDINGS,
    sound: sounds.WAVES,
    x: 391,
    y: 0,
    width: 24,
    height: 18,
    offsetX: -10,
    offsetY: -11,
    frameCount: 3,
    speed: 5
  },
  [spriteTypes.FIELD]: {
    image: images.BUILDINGS,
    sound: null,
    x: 0,
    y: 0,
    width: 42,
    height: 27,
    offsetX: -21,
    offsetY: -16,
    frameCount: 9,
    speed: 0
  },
  [spriteTypes.TENT]: {
    image: images.BUILDINGS,
    sound: null,
    x: 42,
    y: 0,
    width: 23,
    height: 20,
    offsetX: -14,
    offsetY: -14,
    frameCount: 4,
    speed: 0
  },
  [spriteTypes.BOAT]: {
    image: images.BUILDINGS,
    sound: null,
    x: 65,
    y: 0,
    width: 26,
    height: 18,
    offsetX: -13,
    offsetY: -11,
    frameCount: 7,
    speed: 0
  },
  [spriteTypes.PIPE]: {
    image: images.BUILDINGS,
    sound: null,
    x: 91,
    y: 0,
    width: 34,
    height: 21,
    offsetX: -16,
    offsetY: -14,
    frameCount: 5,
    speed: 0
  },
  [spriteTypes.SOS]: {
    image: images.BUILDINGS,
    sound: null,
    x: 125,
    y: 0,
    width: 36,
    height: 19,
    offsetX: -18,
    offsetY: -11,
    frameCount: 7,
    speed: 0
  },
  [spriteTypes.FIREPLACE]: {
    image: images.BUILDINGS,
    sound: null,
    x: 255,
    y: 0,
    width: 21,
    height: 19,
    offsetX: -11,
    offsetY: -15,
    frameCount: 5,
    speed: 0
  },
  [spriteTypes.FIRE]: {
    image: images.BUILDINGS,
    sound: sounds.FIRE,
    x: 276,
    y: 0,
    width: 21,
    height: 28,
    offsetX: -11,
    offsetY: -24,
    frameCount: 3,
    speed: 6
  },
  [spriteTypes.GUY_WALKING_WEST]: {
    image: images.GUY,
    x: 0,
    y: 0,
    width: 7,
    height: 18,
    offsetX: -4,
    offsetY: -17,
    frameCount: 4,
    speed: 20
  },
  [spriteTypes.GUY_WALKING_NORTH]: {
    image: images.GUY,
    x: 7,
    y: 0,
    width: 7,
    height: 18,
    offsetX: -3,
    offsetY: -17,
    frameCount: 4,
    speed: 20
  },
  [spriteTypes.GUY_WALKING_EAST]: {
    image: images.GUY,
    x: 14,
    y: 0,
    width: 7,
    height: 18,
    offsetX: -3,
    offsetY: -17,
    frameCount: 4,
    speed: 20
  },
  [spriteTypes.GUY_WALKING_SOUTH]: {
    image: images.GUY,
    x: 21,
    y: 0,
    width: 7,
    height: 18,
    offsetX: -4,
    offsetY: -17,
    frameCount: 4,
    speed: 20
  },
  [spriteTypes.GUY_SEARCHING]: {
    image: images.GUY,
    x: 28,
    y: 0,
    width: 11,
    height: 14,
    offsetX: -9,
    offsetY: -13,
    frameCount: 4,
    speed: 4
  },
  [spriteTypes.GUY_EATING]: {
    image: images.GUY,
    x: 39,
    y: 0,
    width: 7,
    height: 17,
    offsetX: -3,
    offsetY: -17,
    frameCount: 4,
    speed: 4
  },
  [spriteTypes.GUY_DRINKING]: {
    image: images.GUY,
    x: 46,
    y: 0,
    width: 9,
    height: 13,
    offsetX: -3,
    offsetY: -12,
    frameCount: 5,
    speed: 4
  },
  [spriteTypes.GUY_CHOPPING]: {
    image: images.GUY,
    x: 55,
    y: 0,
    width: 15,
    height: 19,
    offsetX: -8,
    offsetY: -18,
    frameCount: 4,
    speed: 6
  },
  [spriteTypes.GUY_WAITING]: {
    image: images.GUY,
    x: 70,
    y: 0,
    width: 7,
    height: 18,
    offsetX: -4,
    offsetY: -17,
    frameCount: 4,
    speed: 2
  },
  [spriteTypes.GUY_HARROWING]: {
    image: images.GUY,
    x: 78,
    y: 0,
    width: 19,
    height: 18,
    offsetX: -16,
    offsetY: -17,
    frameCount: 4,
    speed: 4
  },
  [spriteTypes.GUY_KNOTTING_NORTH]: {
    image: images.GUY,
    x: 97,
    y: 0,
    width: 8,
    height: 18,
    offsetX: -3,
    offsetY: -17,
    frameCount: 2,
    speed: 1
  },
  [spriteTypes.GUY_KNOTTING_SOUTH]: {
    image: images.GUY,
    x: 98,
    y: 36,
    width: 7,
    height: 18,
    offsetX: -4,
    offsetY: -17,
    frameCount: 2,
    speed: 1
  },
  [spriteTypes.GUY_SLEEPING_TENT]: {
    image: images.GUY,
    x: 105,
    y: 54,
    width: 20,
    height: 10,
    offsetX: -5,
    offsetY: -10,
    frameCount: 2,
    speed: 1
  },
  [spriteTypes.GUY_SLEEPING]: {
    image: images.GUY,
    x: 125,
    y: 36,
    width: 17,
    height: 18,
    offsetX: -3,
    offsetY: -17,
    frameCount: 2,
    speed: 1
  },
  [spriteTypes.GUY_LAYING_DOWN_TENT]: {
    image: images.GUY,
    x: 105,
    y: 0,
    width: 7,
    height: 18,
    offsetX: -3,
    offsetY: -17,
    frameCount: 3,
    speed: 4
  },
  [spriteTypes.GUY_LAYING_DOWN]: {
    image: images.GUY,
    x: 125,
    y: 0,
    width: 17,
    height: 18,
    offsetX: -3,
    offsetY: -17,
    frameCount: 2,
    speed: 2
  },
  [spriteTypes.GUY_STANDING_UP]: {
    image: images.GUY,
    x: 142,
    y: 0,
    width: 9,
    height: 18,
    offsetX: -3,
    offsetY: -17,
    frameCount: 2,
    speed: 2
  },
  [spriteTypes.GUY_FISHING_SWINGING_WEST]: {
    image: images.GUY,
    x: 151,
    y: 0,
    width: 16,
    height: 17,
    offsetX: -11,
    offsetY: -16,
    frameCount: 6,
    speed: 6
  },
  [spriteTypes.GUY_FISHING_SWINGING_NORTH]: {
    image: images.GUY,
    x: 167,
    y: 0,
    width: 16,
    height: 17,
    offsetX: -5,
    offsetY: -16,
    frameCount: 6,
    speed: 6
  },
  [spriteTypes.GUY_FISHING_SWINGING_EAST]: {
    image: images.GUY,
    x: 183,
    y: 0,
    width: 14,
    height: 17,
    offsetX: -7,
    offsetY: -14,
    frameCount: 6,
    speed: 6
  },
  [spriteTypes.GUY_FISHING_SWINGING_SOUTH]: {
    image: images.GUY,
    x: 197,
    y: 0,
    width: 14,
    height: 17,
    offsetX: -7,
    offsetY: -14,
    frameCount: 6,
    speed: 6
  },
  [spriteTypes.GUY_FISHING_WEST]: {
    image: images.GUY,
    x: 211,
    y: 0,
    width: 16,
    height: 16,
    offsetX: -11,
    offsetY: -15,
    frameCount: 4,
    speed: 3
  },
  [spriteTypes.GUY_FISHING_NORTH]: {
    image: images.GUY,
    x: 227,
    y: 0,
    width: 16,
    height: 16,
    offsetX: -5,
    offsetY: -15,
    frameCount: 4,
    speed: 3
  },
  [spriteTypes.GUY_FISHING_EAST]: {
    image: images.GUY,
    x: 243,
    y: 0,
    width: 14,
    height: 15,
    offsetX: -7,
    offsetY: -12,
    frameCount: 4,
    speed: 3
  },
  [spriteTypes.GUY_FISHING_SOUTH]: {
    image: images.GUY,
    x: 257,
    y: 0,
    width: 14,
    height: 15,
    offsetX: -7,
    offsetY: -12,
    frameCount: 4,
    speed: 3
  },
  [spriteTypes.GUY_FISHING_CATCHING_WEST]: {
    image: images.GUY,
    x: 271,
    y: 0,
    width: 16,
    height: 16,
    offsetX: -9,
    offsetY: -15,
    frameCount: 3,
    speed: 2
  },
  [spriteTypes.GUY_FISHING_CATCHING_NORTH]: {
    image: images.GUY,
    x: 285,
    y: 0,
    width: 16,
    height: 16,
    offsetX: -5,
    offsetY: -15,
    frameCount: 3,
    speed: 2
  },
  [spriteTypes.GUY_FISHING_CATCHING_EAST]: {
    image: images.GUY,
    x: 299,
    y: 0,
    width: 14,
    height: 15,
    offsetX: -7,
    offsetY: -12,
    frameCount: 3,
    speed: 2
  },
  [spriteTypes.GUY_FISHING_CATCHING_SOUTH]: {
    image: images.GUY,
    x: 313,
    y: 0,
    width: 14,
    height: 15,
    offsetX: -7,
    offsetY: -12,
    frameCount: 3,
    speed: 2
  },
  [spriteTypes.GUY_HITTING]: {
    image: images.GUY,
    x: 327,
    y: 0,
    width: 12,
    height: 24,
    offsetX: -9,
    offsetY: -23,
    frameCount: 4,
    speed: 7
  },
  [spriteTypes.GUY_PADDLING_WEST]: {
    image: images.GUY,
    x: 339,
    y: 0,
    width: 26,
    height: 21,
    offsetX: -13,
    offsetY: -14,
    frameCount: 6,
    speed: 10
  },
  [spriteTypes.GUY_PADDLING_NORTH]: {
    image: images.GUY,
    x: 365,
    y: 0,
    width: 26,
    height: 21,
    offsetX: -13,
    offsetY: -14,
    frameCount: 6,
    speed: 10
  },
  [spriteTypes.GUY_PADDLING_EAST]: {
    image: images.GUY,
    x: 391,
    y: 0,
    width: 26,
    height: 21,
    offsetX: -13,
    offsetY: -14,
    frameCount: 6,
    speed: 10
  },
  [spriteTypes.GUY_PADDLING_SOUTH]: {
    image: images.GUY,
    x: 417,
    y: 0,
    width: 26,
    height: 21,
    offsetX: -13,
    offsetY: -14,
    frameCount: 6,
    speed: 10
  },
  [spriteTypes.GUY_FISHING_SWINGING_BOAT]: {
    image: images.GUY,
    x: 443,
    y: 0,
    width: 26,
    height: 25,
    offsetX: -13,
    offsetY: -18,
    frameCount: 6,
    speed: 6
  },
  [spriteTypes.GUY_FISHING_BOAT]: {
    image: images.GUY,
    x: 469,
    y: 0,
    width: 26,
    height: 25,
    offsetX: -13,
    offsetY: -18,
    frameCount: 4,
    speed: 3
  },
  [spriteTypes.GUY_FISHING_CATCHING_BOAT]: {
    image: images.GUY,
    x: 495,
    y: 0,
    width: 26,
    height: 25,
    offsetX: -13,
    offsetY: -18,
    frameCount: 3,
    speed: 2
  },
  [spriteTypes.GUY_DIVING_JUMPING]: {
    image: images.GUY,
    x: 521,
    y: 0,
    width: 26,
    height: 27,
    offsetX: -13,
    offsetY: -20,
    frameCount: 5,
    speed: 5
  },
  [spriteTypes.GUY_DIVING]: {
    image: images.GUY,
    x: 547,
    y: 0,
    width: 26,
    height: 17,
    offsetX: -13,
    offsetY: -10,
    frameCount: 4,
    speed: 3
  },
  [spriteTypes.GUY_DIVING_CLIMBING]: {
    image: images.GUY,
    x: 573,
    y: 0,
    width: 26,
    height: 17,
    offsetX: -13,
    offsetY: -10,
    frameCount: 2,
    speed: 2
  },
  [spriteTypes.GUY_HAMMERING]: {
    image: images.GUY,
    x: 599,
    y: 0,
    width: 9,
    height: 18,
    offsetX: -4,
    offsetY: -18,
    frameCount: 2,
    speed: 4
  },
  [spriteTypes.GUY_CLIMBING_UP]: {
    image: images.GUY,
    x: 608,
    y: 0,
    width: 7,
    height: 34,
    offsetX: -4,
    offsetY: -34,
    frameCount: 6,
    speed: 2
  },
  [spriteTypes.GUY_CLIMBING_DOWN]: {
    image: images.GUY,
    x: 615,
    y: 0,
    width: 7,
    height: 34,
    offsetX: -4,
    offsetY: -34,
    frameCount: 6,
    speed: 2
  },
  [spriteTypes.GUY_HAMMERING_TOP]: {
    image: images.GUY,
    x: 622,
    y: 0,
    width: 7,
    height: 34,
    offsetX: -3,
    offsetY: -34,
    frameCount: 2,
    speed: 4
  },
  [spriteTypes.GUY_LAYING_DOWN_HOUSE]: {
    image: images.GUY,
    x: 631,
    y: 0,
    width: 9,
    height: 34,
    offsetX: -3,
    offsetY: -34,
    frameCount: 3,
    speed: 2
  },
  [spriteTypes.GUY_SLEEPING_HOUSE]: {
    image: images.GUY,
    x: 640,
    y: 0,
    width: 10,
    height: 34,
    offsetX: 9,
    offsetY: -32,
    frameCount: 2,
    speed: 1
  },
  [spriteTypes.GUY_STANDING_UP_HOUSE]: {
    image: images.GUY,
    x: 650,
    y: 0,
    width: 9,
    height: 34,
    offsetX: -3,
    offsetY: -34,
    frameCount: 3,
    speed: 2
  },
  [spriteTypes.GUY_LIGHTNING]: {
    image: images.GUY,
    x: 659,
    y: 0,
    width: 19,
    height: 18,
    offsetX: -3,
    offsetY: -17,
    frameCount: 6,
    speed: 5
  },
  [spriteTypes.GUY_LOOKING]: {
    image: images.GUY,
    x: 678,
    y: 0,
    width: 10,
    height: 18,
    offsetX: -6,
    offsetY: -17,
    frameCount: 4,
    speed: 1
  },
  [spriteTypes.GUY_SHOVELING]: {
    image: images.GUY,
    x: 688,
    y: 0,
    width: 17,
    height: 19,
    offsetX: -14,
    offsetY: -17,
    frameCount: 10,
    speed: 3
  },
  [spriteTypes.GUY_SAILING]: {
    image: images.BUILDINGS,
    x: 297,
    y: 0,
    width: 48,
    height: 38,
    offsetX: -30,
    offsetY: -29,
    frameCount: 4,
    speed: 10
  },
  [spriteTypes.GUY_TANKING]: {
    image: images.BUILDINGS,
    x: 345,
    y: 0,
    width: 46,
    height: 40,
    offsetX: -22,
    offsetY: -29,
    frameCount: 6,
    speed: 3
  },
  [spriteTypes.GUY_SWIMMING]: {
    image: images.GUY,
    x: 705,
    y: 0,
    width: 15,
    height: 9,
    offsetX: -8,
    offsetY: -6,
    frameCount: 4,
    speed: 10
  },
  [spriteTypes.GUY_DYING]: {
    image: images.GUY,
    x: 743,
    y: 0,
    width: 16,
    height: 10,
    offsetX: -9,
    offsetY: -7,
    frameCount: 6,
    speed: 1
  },
  [spriteTypes.GUY_DYING_BOAT]: {
    image: images.GUY,
    x: 759,
    y: 0,
    width: 26,
    height: 18,
    offsetX: -14,
    offsetY: -11,
    frameCount: 6,
    speed: 1
  },
  [spriteTypes.GUY_WAITING_BOAT]: {
    image: images.GUY,
    x: 0,
    y: 72,
    width: 26,
    height: 20,
    offsetX: -14,
    offsetY: -13,
    frameCount: 4,
    speed: 2
  },
  [spriteTypes.GUY_SLINGING]: {
    image: images.GUY,
    x: 720,
    y: 0,
    width: 23,
    height: 20,
    offsetX: -3,
    offsetY: -19,
    frameCount: 5,
    speed: 4
  },
};

export default sprites;