const actionTypes = {
  STOPPING_GAME: 'stoppingGame',
  RESTARTING_GAME: 'restartingGame',
  DYING: 'dying',
  ENDING_DAY: 'endingDay',
  RESTARTING_DAY: 'restartingDay',
  ARRIVING: 'arriving',
  LEAVING: 'leaving',
  STOPPING: 'stopping',
  DOCKING: 'docking',
  UNDOCKING: 'undocking',
  SEARCHING: 'searching',
  CONSUMING: 'consuming',
  SLEEPING: 'sleeping',
  CHOPPING: 'chopping',
  FISHING: 'fishing',
  LIGHTNING: 'lightning',
  LOOKING: 'looking',
  SHOVELING: 'shoveling',
  SLINGING: 'slinging',
  CONSTRUCTING_TENT: 'constructingTent',
  CONSTRUCTING_FIELD: 'constructingField',
  CONSTRUCTING_BOAT: 'constructingBoat',
  CONSTRUCTING_PIPE: 'constructingPipe',
  CONSTRUCTING_SOS: 'constructingSos',
  CONSTRUCTING_LADDER: 'constructingLadder',
  CONSTRUCTING_PLATFORM: 'constructingPlatform',
  CONSTRUCTING_TREE_HOUSE: 'constructingTreeHouse',
  CONSTRUCTING_FIREPLACE: 'constructingFireplace',
  DESTROYING: 'constructingDestroy',
};

export default actionTypes;