import spriteTypes from '../images/spriteTypes.js';

const creditGuySprites = [
  spriteTypes.GUY_WALKING_WEST,
  spriteTypes.GUY_WALKING_NORTH,
  spriteTypes.GUY_WALKING_EAST,
  spriteTypes.GUY_WALKING_SOUTH,
  spriteTypes.GUY_SEARCHING,
  spriteTypes.GUY_EATING,
  spriteTypes.GUY_DRINKING,
  spriteTypes.GUY_CHOPPING,
  spriteTypes.GUY_HARROWING,
  spriteTypes.GUY_LIGHTNING,
  spriteTypes.GUY_LOOKING,
  spriteTypes.GUY_SHOVELING,
  spriteTypes.GUY_KNOTTING_NORTH,
  spriteTypes.GUY_KNOTTING_SOUTH,
  spriteTypes.GUY_SLINGING,
  spriteTypes.GUY_LAYING_DOWN,
  spriteTypes.GUY_SLEEPING,
  spriteTypes.GUY_STANDING_UP,
  spriteTypes.GUY_FISHING_SWINGING_WEST,
  spriteTypes.GUY_FISHING_WEST,
  spriteTypes.GUY_FISHING_CATCHING_WEST,
  spriteTypes.GUY_FISHING_SWINGING_NORTH,
  spriteTypes.GUY_FISHING_NORTH,
  spriteTypes.GUY_FISHING_CATCHING_NORTH,
  spriteTypes.GUY_FISHING_SWINGING_EAST,
  spriteTypes.GUY_FISHING_EAST,
  spriteTypes.GUY_FISHING_CATCHING_EAST,
  spriteTypes.GUY_FISHING_SWINGING_SOUTH,
  spriteTypes.GUY_FISHING_SOUTH,
  spriteTypes.GUY_FISHING_CATCHING_SOUTH,
  spriteTypes.GUY_HITTING,
  spriteTypes.GUY_HAMMERING,
  spriteTypes.GUY_CLIMBING_UP,
  spriteTypes.GUY_CLIMBING_DOWN,
  spriteTypes.GUY_WAITING,
  spriteTypes.GUY_LAYING_DOWN,
  spriteTypes.GUY_DYING,
  spriteTypes.GUY_SAILING,
  spriteTypes.GUY_TANKING,
  spriteTypes.GUY_SWIMMING,
  spriteTypes.GUY_PADDLING_WEST,
  spriteTypes.GUY_PADDLING_NORTH,
  spriteTypes.GUY_PADDLING_EAST,
  spriteTypes.GUY_PADDLING_SOUTH,
  spriteTypes.GUY_FISHING_SWINGING_BOAT,
  spriteTypes.GUY_FISHING_BOAT,
  spriteTypes.GUY_FISHING_CATCHING_BOAT,
  spriteTypes.GUY_DIVING_JUMPING,
  spriteTypes.GUY_DIVING,
  spriteTypes.GUY_DIVING_CLIMBING,
  spriteTypes.GUY_WAITING_BOAT,
  spriteTypes.GUY_DYING_BOAT,
];

export default creditGuySprites;