import tileTypes from './tileTypes.js';
import directions from '../directions.js';

const allowedNeighbors = {
  [tileTypes.FLAT]: {
    [directions.WEST]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_WEST, heightChange: -1 },
      { type: tileTypes.SLOPE_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: -1 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: -1 },
    ],
    [directions.NORTH]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_NORTH, heightChange: -1 },
      { type: tileTypes.SLOPE_SOUTH, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: -1 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: -1 },
    ],
    [directions.EAST]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_WEST, heightChange: 0 },
      { type: tileTypes.SLOPE_EAST, heightChange: -1 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: -1 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: -1 },
    ],
    [directions.SOUTH]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_NORTH, heightChange: 0 },
      { type: tileTypes.SLOPE_SOUTH, heightChange: -1 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: -1 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: -1 },
    ],
  },
  [tileTypes.SLOPE_NORTH]: {
    [directions.WEST]: [
      { type: tileTypes.SLOPE_NORTH, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: 0 },
    ],
    [directions.NORTH]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_NORTH, heightChange: -1 },
      { type: tileTypes.SLOPE_SOUTH, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: -1 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: -1 },
    ],
    [directions.EAST]: [
      { type: tileTypes.SLOPE_NORTH, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: 0 },
    ],
    [directions.SOUTH]: [
      { type: tileTypes.FLAT, heightChange: 1 },
      { type: tileTypes.SLOPE_NORTH, heightChange: 1 },
      { type: tileTypes.SLOPE_SOUTH, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 1 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 1 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: 0 },
    ],
  },
  [tileTypes.SLOPE_WEST]: {
    [directions.WEST]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_WEST, heightChange: -1 },
      { type: tileTypes.SLOPE_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: -1 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: -1 },
    ],
    [directions.NORTH]: [
      { type: tileTypes.SLOPE_WEST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: 0 },
    ],
    [directions.EAST]: [
      { type: tileTypes.FLAT, heightChange: 1 },
      { type: tileTypes.SLOPE_WEST, heightChange: 1 },
      { type: tileTypes.SLOPE_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 1 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 1 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: 0 },
    ],
    [directions.SOUTH]: [
      { type: tileTypes.SLOPE_WEST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: 0 },
    ],
  },
  [tileTypes.SLOPE_SOUTH]: {
    [directions.WEST]: [
      { type: tileTypes.SLOPE_SOUTH, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: 0 },
    ],
    [directions.NORTH]: [
      { type: tileTypes.FLAT, heightChange: 1 },
      { type: tileTypes.SLOPE_NORTH, heightChange: 0 },
      { type: tileTypes.SLOPE_SOUTH, heightChange: 1 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 1 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 1 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: 0 },
    ],
    [directions.EAST]: [
      { type: tileTypes.SLOPE_SOUTH, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: 0 },
    ],
    [directions.SOUTH]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_NORTH, heightChange: 0 },
      { type: tileTypes.SLOPE_SOUTH, heightChange: -1 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: -1 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: -1 },
    ],
  },
  [tileTypes.SLOPE_EAST]: {
    [directions.WEST]: [
      { type: tileTypes.FLAT, heightChange: 1 },
      { type: tileTypes.SLOPE_WEST, heightChange: 0 },
      { type: tileTypes.SLOPE_EAST, heightChange: 1 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 1 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 1 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: 0 },
    ],
    [directions.NORTH]: [
      { type: tileTypes.SLOPE_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: 0 },
    ],
    [directions.EAST]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_WEST, heightChange: 0 },
      { type: tileTypes.SLOPE_EAST, heightChange: -1 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: -1 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: -1 },
    ],
    [directions.SOUTH]: [
      { type: tileTypes.SLOPE_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: 0 },
    ],
  },
  [tileTypes.RIDGE_NORTH_EAST]: {
    [directions.WEST]: [
      { type: tileTypes.SLOPE_NORTH, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: 0 },
    ],
    [directions.NORTH]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_NORTH, heightChange: -1 },
      { type: tileTypes.SLOPE_SOUTH, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: -1 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: -1 },
    ],
    [directions.EAST]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_WEST, heightChange: 0 },
      { type: tileTypes.SLOPE_EAST, heightChange: -1 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: -1 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: -1 },
    ],
    [directions.SOUTH]: [
      { type: tileTypes.SLOPE_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: 0 },
    ],
  },
  [tileTypes.RIDGE_NORTH_WEST]: {
    [directions.WEST]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_WEST, heightChange: -1 },
      { type: tileTypes.SLOPE_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: -1 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: -1 },
    ],
    [directions.NORTH]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_NORTH, heightChange: -1 },
      { type: tileTypes.SLOPE_SOUTH, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: -1 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: -1 },
    ],
    [directions.EAST]: [
      { type: tileTypes.SLOPE_NORTH, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: 0 },
    ],
    [directions.SOUTH]: [
      { type: tileTypes.SLOPE_WEST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: 0 },
    ],
  },
  [tileTypes.RIDGE_SOUTH_WEST]: {
    [directions.WEST]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_WEST, heightChange: -1 },
      { type: tileTypes.SLOPE_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: -1 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: -1 },
    ],
    [directions.NORTH]: [
      { type: tileTypes.SLOPE_WEST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: 0 },
    ],
    [directions.EAST]: [
      { type: tileTypes.SLOPE_SOUTH, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: 0 },
    ],
    [directions.SOUTH]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_NORTH, heightChange: 0 },
      { type: tileTypes.SLOPE_SOUTH, heightChange: -1 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: -1 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: -1 },
    ],
  },
  [tileTypes.RIDGE_SOUTH_EAST]: {
    [directions.WEST]: [
      { type: tileTypes.SLOPE_SOUTH, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: 0 },
    ],
    [directions.NORTH]: [
      { type: tileTypes.SLOPE_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: 0 },
    ],
    [directions.EAST]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_WEST, heightChange: 0 },
      { type: tileTypes.SLOPE_EAST, heightChange: -1 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: -1 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: -1 },
    ],
    [directions.SOUTH]: [
      { type: tileTypes.FLAT, heightChange: 0 },
      { type: tileTypes.SLOPE_NORTH, heightChange: 0 },
      { type: tileTypes.SLOPE_SOUTH, heightChange: -1 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: -1 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: -1 },
    ],
  },
  [tileTypes.CANYON_SOUTH_EAST]: {
    [directions.WEST]: [
      { type: tileTypes.FLAT, heightChange: 1 },
      { type: tileTypes.SLOPE_WEST, heightChange: 0 },
      { type: tileTypes.SLOPE_EAST, heightChange: 1 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 1 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 1 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: 0 },
    ],
    [directions.NORTH]: [
      { type: tileTypes.FLAT, heightChange: 1 },
      { type: tileTypes.SLOPE_NORTH, heightChange: 0 },
      { type: tileTypes.SLOPE_SOUTH, heightChange: 1 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 1 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 1 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: 0 },
    ],
    [directions.EAST]: [
      { type: tileTypes.SLOPE_SOUTH, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: 0 },
    ],
    [directions.SOUTH]: [
      { type: tileTypes.SLOPE_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: 0 },
    ],
  },
  [tileTypes.CANYON_NORTH_EAST]: {
    [directions.WEST]: [
      { type: tileTypes.FLAT, heightChange: 1 },
      { type: tileTypes.SLOPE_WEST, heightChange: 0 },
      { type: tileTypes.SLOPE_EAST, heightChange: 1 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 1 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 1 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: 0 },
    ],
    [directions.NORTH]: [
      { type: tileTypes.SLOPE_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: 0 },
    ],
    [directions.EAST]: [
      { type: tileTypes.SLOPE_NORTH, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: 0 },
    ],
    [directions.SOUTH]: [
      { type: tileTypes.FLAT, heightChange: 1 },
      { type: tileTypes.SLOPE_NORTH, heightChange: 1 },
      { type: tileTypes.SLOPE_SOUTH, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 1 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 1 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: 0 },
    ],
  },
  [tileTypes.CANYON_NORTH_WEST]: {
    [directions.WEST]: [
      { type: tileTypes.SLOPE_NORTH, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: 0 },
    ],
    [directions.NORTH]: [
      { type: tileTypes.SLOPE_WEST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: 0 },
    ],
    [directions.EAST]: [
      { type: tileTypes.FLAT, heightChange: 1 },
      { type: tileTypes.SLOPE_WEST, heightChange: 1 },
      { type: tileTypes.SLOPE_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 1 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 1 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: 0 },
    ],
    [directions.SOUTH]: [
      { type: tileTypes.FLAT, heightChange: 1 },
      { type: tileTypes.SLOPE_NORTH, heightChange: 1 },
      { type: tileTypes.SLOPE_SOUTH, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_EAST, heightChange: 1 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 1 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_WEST, heightChange: 0 },
    ],
  },
  [tileTypes.CANYON_SOUTH_WEST]: {
    [directions.WEST]: [
      { type: tileTypes.SLOPE_SOUTH, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: 0 },
    ],
    [directions.NORTH]: [
      { type: tileTypes.FLAT, heightChange: 1 },
      { type: tileTypes.SLOPE_NORTH, heightChange: 0 },
      { type: tileTypes.SLOPE_SOUTH, heightChange: 1 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 1 },
      { type: tileTypes.RIDGE_SOUTH_EAST, heightChange: 1 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: 0 },
    ],
    [directions.EAST]: [
      { type: tileTypes.FLAT, heightChange: 1 },
      { type: tileTypes.SLOPE_WEST, heightChange: 1 },
      { type: tileTypes.SLOPE_EAST, heightChange: 0 },
      { type: tileTypes.RIDGE_NORTH_WEST, heightChange: 1 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 1 },
      { type: tileTypes.CANYON_SOUTH_EAST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_EAST, heightChange: 0 },
    ],
    [directions.SOUTH]: [
      { type: tileTypes.SLOPE_WEST, heightChange: 0 },
      { type: tileTypes.RIDGE_SOUTH_WEST, heightChange: 0 },
      { type: tileTypes.CANYON_NORTH_WEST, heightChange: 0 },
    ],
  },
};

export default allowedNeighbors;